# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G9u6LRNRmKb5aYl2D5p2_5-8Z81f0PpH
"""

!git clone https://github.com/pjreddie/darknet

!cd darknet

!make

cd darknet

make

!make

